In [2]:
import pandas as pd
import numpy as np

import plotly.express as px
import plotly.graph_objects as go
import plotly.io as pio
pio.templates

import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [4]:
df=pd.read_csv("/Users/ayaanhaq/Documents/Machine Learning/BundesligaMatchPredictor/Bundesliga ML/Bundesliga Match Data/23_24.csv")

print(df.head())
print(df.columns)
print(df.info())

  Div        Date   Time       HomeTeam       AwayTeam  \
0  D1  18/08/2023  19:30  Werder Bremen  Bayern Munich   
1  D1  19/08/2023  14:30       Augsburg     M'gladbach   
2  D1  19/08/2023  14:30     Hoffenheim       Freiburg   
3  D1  19/08/2023  14:30     Leverkusen     RB Leipzig   
4  D1  19/08/2023  14:30      Stuttgart         Bochum   

   Full Time Home Team Goals  Full Time Away Team Goals Full Time Result  \
0                          0                          4                A   
1                          4                          4                D   
2                          1                          2                A   
3                          3                          2                H   
4                          5                          0                H   

   Half Time Home Goals  Half Time Away Team Goals  ...  \
0                     0                          1  ...   
1                     3                          3  ...   
2                

In [5]:
data= pd.DataFrame(df)
data.head()

Div        Date   Time       HomeTeam       AwayTeam  \
0  D1  18/08/2023  19:30  Werder Bremen  Bayern Munich   
1  D1  19/08/2023  14:30       Augsburg     M'gladbach   
2  D1  19/08/2023  14:30     Hoffenheim       Freiburg   
3  D1  19/08/2023  14:30     Leverkusen     RB Leipzig   
4  D1  19/08/2023  14:30      Stuttgart         Bochum   

   Full Time Home Team Goals  Full Time Away Team Goals Full Time Result  \
0                          0                          4                A   
1                          4                          4                D   
2                          1                          2                A   
3                          3                          2                H   
4                          5                          0                H   

   Half Time Home Goals  Half Time Away Team Goals  ...  \
0                     0                          1  ...   
1                     3                          3  ...   
2                     0                          2  ...   
3                     2                          1  ...   
4                     2                          0  ...   

  Home Team Shots on Target  Away Team Shots on Target  \
0                         1                         10   
1                         8                          6   
2                         5                          8   
3                         7                          6   
4                         9                          1   

   Home Team Fouls Committed  Away Team Fouls Commited  Home Team Corners  \
0                         16                        11                  0   
1                          9                        14                  8   
2                          9                         9                  4   
3                         13                        10                  4   
4                          5                        12                  7   

   Away Team Corners  Home Team Yellow Cards  Away Team Yellow Cards  \
0                  6                       2                       1   
1                  7                       1                       2   
2                  2                       0                       1   
3                  5                       1                       2   
4                  0                       1                       1   

   Home Team Red Cards  Away Team Red Cards  
0                    0                    0  
1                    0                    0  
2                    0                    0  
3                    0                    0  
4                    0                    0  

[5 rows x 23 columns]

In [6]:
X= df.drop(columns=["Full Time Result", "Half Time Result"])
y= df["Full Time Result"]

In [7]:
print(df.shape)

(306, 23)


In [8]:
sns.pairplot(data, height=2.5)
plt.tight_layout()

In [9]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

X= df.drop(columns=["Div","Full Time Result", "Half Time Result","Date","Time","HomeTeam","AwayTeam"], axis=1)
y=df["Full Time Result"]
X_train, X_test, y_train, y_test= train_test_split(X, y, test_size=0.2, random_state=42)


In [10]:
clf=RandomForestClassifier()
clf.fit(X_train, y_train)

RandomForestClassifier()

In [19]:
accuracy= clf.score(X_test, y_test)
print(f"Accuracy: {accuracy:.2f}")

Accuracy: 0.97


In [20]:
y_pred=clf.predict(X_test)

In [13]:
from sklearn.metrics import classification_report, confusion_matrix

print("Confusion matrix: ")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report: ")
print(classification_report(y_test, y_pred))

Confusion matrix: 
[[13  2  0]
 [ 0 18  0]
 [ 0  0 29]]

Classification Report: 
              precision    recall  f1-score   support

           A       1.00      0.87      0.93        15
           D       0.90      1.00      0.95        18
           H       1.00      1.00      1.00        29

    accuracy                           0.97        62
   macro avg       0.97      0.96      0.96        62
weighted avg       0.97      0.97      0.97        62



In [18]:
comparison= pd.DataFrame({"Actual": y_test, "predicted": y_pred})
print(comparison.tail(62))

    Actual predicted
182      D         D
154      A         A
111      H         H
203      H         H
60       H         H
..     ...       ...
104      H         H
303      H         H
196      D         D
230      A         A
271      A         A

[62 rows x 2 columns]
